python3 -u experiment_galaxy.py \
	-e 'logging' \
	-nPerm 100 \
	-sign 0.05 \
	-rId 1 \
	-datafolder 'results/galaxy_results' \
	-lr 0.00008\
	-epochs 200 \
	-sigma 12288 \
	-sigma0 17 \
	-batch_size 250 \
	-epsilon 0.6 \
	-parallel False \
	-deep  True \
	-is_image True \
	-validation True \
	-repetitions 1 \
	-vary_size True \
